### ISSUE TITLE
Add jsbundle property to global metadata

### ISSUE THREAD

**Issue by webketje** [metalsmith/js-bundle#5]
Adding `jsbundle` property to the global metadata with a structure `jsbundle: { 'source-file.js':  { src: 'destination-file.js', async:  }}}`.

This allows templates to do: 

```njk
{% for script in jsbundle %}
<script {% for attr,value in script %} {{attr}}="{{value}}"{% endfor %}></script>
{% endfor %}
```

As well as use a mechanism whereby file front-matter specifies the scripts to load:
```yaml
---
scripts:
  - 'assets/js/common/source.js'
  - 'assets/js/app/source.js':
     async: true
     integrity: 'abcdefg'
---
```
```njk
{% for script in jsbundle %}
{% if typeof script === 'string' %}
<script src="{{ script }}"></script>
{% else %}
<script {% for attr,value in script %} {{attr}}="{{value}}"{% endfor %}></script>
{% endfor %}
```
